### PR TITLE
Deal with patched kernel build versions

### PR DESCRIPTION
**Pull request by brendangregg**

### CODE REVIEW

**Comment by ajor** [comment]
I think this is probably the right way to go to get the kernel version. I originally wanted it to be found at run time so the same binary could be used on multiple kernels, but obviously that's not working. Just holding off merging for now while I do some testing and look into the issue at https://github.com/ajor/bpftrace/issues/8#issuecomment-370154992

**Comment by brendangregg** [comment]
Ok. I think this is the same approach that bcc uses, as it pulls the "version" from section headers, and sets:

```
src/cc/export/helpers.h:unsigned _version SEC("version") = LINUX_VERSION_CODE;
```

@drzaeus77 may be able to confirm offhand.

**Comment by drzaeus77** [comment]
It was meant as a sanity check on the API, like a lightweight version of what goes on for kernel module loading. It must match the currently running kernel.

**Comment by ahrens** [comment]
I also needed this patch to get bpftrace to work.  This is on Ubuntu 18.04.

**Comment by ajor** [comment]
I've made a change based off this, which first tries the LINUX_VERSION_CODE as in this patch and then falls back to the old method if that fails

**Pull request closed without merging**
